### PR TITLE
Handle pyproject.toml with no `source`

### PR DESCRIPTION
**Pull request by tony**
Hi! Thank you for the project.

This is a change I had to make locally to `poetry_to_uv` for it to continue after not finding a `source`.

```
Traceback (most recent call last):
  File "~/projects/project/.venv/bin/poetry_to_uv", line 8, in <module>
    sys.exit(cli_entrypoint())
  File "~/projects/project/.venv/lib/python3.10/site-packages/poetry_to_uv/__main__.py", line 35, in cli_entrypoint
    poetry_to_uv()
  File "~/projects/project/.venv/lib/python3.10/site-packages/poetry_to_uv/convertor.py", line 249, in __call__
    pyproject_config = self._convert_poetry_to_uv_pyproject(
  File "~/projects/project/.venv/lib/python3.10/site-packages/poetry_to_uv/convertor.py", line 151, in _convert_poetry_to_uv_pyproject
    pyproject_config.get("project").remove("source")
  File "~/projects/project/.venv/lib/python3.10/site-packages/tomlkit/items.py", line 1473, in remove
    self._value.remove(key)
  File "~/projects/project/.venv/lib/python3.10/site-packages/tomlkit/container.py", line 354, in remove
    raise NonExistentKey(key)
tomlkit.exceptions.NonExistentKey: 'Key "source" does not exist.'
```

### CODE REVIEW

**Review by PacificGilly — APPROVED** [review]

**Comment by xymz** [comment]
I faced same trouble in 0.0.3 and tried to contribute for this, but there is already merged pr. So I wonder when will you update the package. I took a look #2 also and I believe it could be a good improvement but, this fix is more urgent. Could you consider update package with this?

**Comment by PacificGilly** [comment]
@tony @xymz apologies for the delay. I've now released v0.0.4 of this package now with this fix. Thanks again for your contribution to this little package. Feel free to raise any more PRs you like and we can look into getting them released too 🙂

**Comment by tony** [comment]
Thank you @PacificGilly!

**Comment by xymz** [comment]
@PacificGilly Thank you!

**Pull request merged**
